services:
  bot:
    build: .
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      DB_FILE_NAME: "file:data/bot.db"
    restart: unless-stopped
    volumes:
      - iris-data:/app/data

volumes:
  iris-data:
